name: Frontend CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  prepare:
    name: prepare Environment
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

#      - name: Cache node modules
#        uses: actions/cache@v2
#        env:
#          cache-name: cache-node-modules
#        with:
#          path: ~/.yarn
#          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn-lock.json') }}
#          restore-keys: |
#            ${{ runner.os }}-build-${{ env.cache-name }}-
#            ${{ runner.os }}-build-
#            ${{ runner.os }}-

      # Runs a single command using the runners shell
      - run: cd frontend && yarn install --frozen-lockfile

      - uses: actions/upload-artifact@v2
        with:
          path: node_modules

  lint:
    name: âœ… Lint
    needs: [prepare]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: cd frontend && yarn lint
